[project]
authors = [
  {email = "engineering@canvasmedical.com", name = "Canvas Team"}
]
dependencies = [
  "canvas[test-utils]"
]
description = "A plugin that adds visualization capabilities to patient vital signs in the chart summary"
license = "MIT"
name = "vitals_visualizer_plugin"
readme = "vitals_visualizer_plugin/README.md"
requires-python = ">=3.11"
version = "0.1.0"

[tool.pytest.ini_options]
python_files = ["*_tests.py", "test_*.py", "tests.py"]
