[project]
authors = [
  {email = "engineering@canvasmedical.com", name = "Canvas Team"}
]
dependencies = [
  "canvas[test-utils]"
]
description = "A plugin that groups Psychiatry conditions and medications in the patient summary chart."
license = "MIT"
name = "patient_summary_chart_groups"
readme = "patient_summary_chart_groups/README.md"
requires-python = ">=3.11"
version = "0.0.1"

[tool.pytest.ini_options]
python_files = ["*_tests.py", "test_*.py", "tests.py"]
