[project]
authors = [
  {email = "engineering@canvasmedical.com", name = "Canvas Team"}
]
dependencies = [
  "canvas[test-utils]"
]
description = "A plugin to interact with a Canvas Instance"
license = "MIT"
name = "my_first_plugin"
readme = "my_first_plugin/README.md"
requires-python = ">=3.11"
version = "0.1.1"

[tool.pytest.ini_options]
python_files = ["*_tests.py", "test_*.py", "tests.py"]
